# Generated by Django 5.1.1 on 2024-10-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoryname', models.CharField(blank=True, max_length=100, null=True)),
                ('Categoryimage', models.ImageField(blank=True, null=True, upload_to='categoryImage')),
                ('Descriptinon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
