# Generated by Django 5.1.1 on 2024-10-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0002_rename_descriptinon_categorydb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selectproduct', models.CharField(blank=True, max_length=100, null=True)),
                ('Productname', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('MRP', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufactured', models.CharField(blank=True, max_length=100, null=True)),
                ('Productimage1', models.ImageField(blank=True, null=True, upload_to='Productimage')),
                ('Productimage2', models.ImageField(blank=True, null=True, upload_to='Productimage')),
                ('Productimage3', models.ImageField(blank=True, null=True, upload_to='Productimage')),
            ],
        ),
    ]
