# Generated by Django 5.1.1 on 2024-10-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0003_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='MRP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
