# Generated by Django 5.1.1 on 2024-10-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0004_alter_productdb_mrp_alter_productdb_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='MRP',
            new_name='Mrp',
        ),
    ]
