# Generated by Django 5.1.1 on 2024-10-15 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0005_rename_mrp_productdb_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Quantity',
        ),
    ]
