# Generated by Django 5.1.1 on 2024-10-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0006_remove_productdb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
