# Generated by Django 5.1.1 on 2024-11-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
